site_name: My Docs

theme:
  name: material
  features:
    - header.autohide # hide header on scroll
    - navigation.sections # fold left side children
    - navigation.tabs
  palette: 
    - scheme: slate # Palette toggle for dark mode
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default # Palette toggle for light mode
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
nav:
  - Home: index.md
  - Test: https://google.com
  # - "<p>LinkedIn &nbsp<i class='fa-solid fa-arrow-up-right-from-square'></i></p>": foo

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css
